# .github/workflows/ci-cd.yml
name: CI/CD → ECR & App Runner

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # para OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::127214193939:role/GitHubActionsECRPushRole
        aws-region: eu-west-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: mi-servicio-pdf
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

  # Opcional: forzar redeploy vía App Runner API
  redeploy-apprunner:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Redeploy App Runner
      uses: andresz1/aws-apprunner-deploy@v1
      with:
        service-arn: arn:aws:apprunner:eu-west-1:127214193939:service/pdf-renderer/50f43387fe1642129e3a5fabbe0471da
        aws-region: eu-west-1
